### ISSUE TITLE
Slide Menu Control Buttons

### ISSUE THREAD

**Issue by chris-haigh** [grubersjoe/slide-menu#1]
I've just come across this and it's exactly what I was looking for.

I have set everything up as per the instructions and I can get it to work when I use the API to manually trigger the menu opening, however none of the buttons work by default.

I'm not getting any errors or anything from when I click the buttons, just nothing happening at all.

Any ideas what I could be missing?

**Comment by grubersjoe** [comment]
Have you specified the correct ID of the menu? 

```html
<a class="slide-menu-control" data-target="foo" data-action="open">Open</a>
```

The `data-target` needs to match exactly the ID of you menu. So in this case you'd need a HTML structure like this:

```html
<nav class="slide-menu" id="foo">
    <ul>
       <!-- ... -->
    </ul>
</nav>
```
As described at the bottom of the README the `data-target` can only be ommited if the button is _inside_ the `.slide-menu`. Nethertheless it can't harm to always set it explicitly.

I've just tested it again with a minimal example and everything works here as expected:

```sh
bower install slide-menu
```

```html
<!DOCTYPE html>
<html>
<head>
    <title>Test</title>

    <link rel="stylesheet" href="bower_components/slide-menu/dist/styles/slide-menu.css">
</head>
<body>
    <nav class="slide-menu" id="my-menu">
        <ul>
            <li>
                <a>Home</a>
                <ul>
                    <li><a>Submenu entry 1</a></li>
                    <li><a>Submenu entry 2</a></li>
                    <li><a>Submenu entry 3</a></li>
                </ul>
            </li>
            <li>
                <a href="/blog">Blog</a>
            </li>
            <li>
                <a href="/about">About</a>
                <ul>
                    <li><a>Submenu entry 1</a></li>
                    <li><a>Submenu entry 2</a></li>
                </ul>
            </li>
        </ul>
    </nav>

    <button type="button" class="slide-menu-control" data-target="my-menu" data-action="open">Open</button>
    <button type="button" class="slide-menu-control" data-target="my-menu" data-action="close">Close</button>
    <button type="button" class="slide-menu-control" data-target="my-menu" data-action="back">Back</button>

    <script src="bower_components/jquery/dist/jquery.min.js"></script>
    <script src="bower_components/slide-menu/dist/scripts/slide-menu.js"></script>

    <script>
        $(document).ready(function () {
            var menu = $('#my-menu').slideMenu({
                submenuLinkAfter: ' >',
                backLinkBefore  : '< ',
            });

            menu.open();
        });
    </script>
</body>
</html>
```
Did this help?

**Comment by chris-haigh** [comment]
Yeah i've got all that stuff done correctly.

The slide controls within the menu itself don't work either, so i'm going to guess i've got a conflict with some existing script somewhere.

**Comment by grubersjoe** [comment]
You could try disabling other scripts. If it starts to work at one point then this sounds plausible.  Unfortunately I can't help with this situation... Good luck anyway!

**Comment by chris-haigh** [comment]
Yeah I totally understand. I've just written a short bit of script to manually control the buttons, so it's all working now.

Thanks again.
