### ISSUE TITLE
Breaking change after update 1.1.3

### ISSUE THREAD

**Issue by peshrawahmed** [grubersjoe/slide-menu#12]
Hi, 
I have updated from 1.0.13 to 1.1.3 and see that it breaks the code while using webpack`(did not tested outside of webpack)`

The following code is woring on 1.0.13 but giving error on 1.1.3: 
```
import '@grubersjoe/slide-menu';
var win = window;

win.document.addEventListener('DOMContentLoaded', function () {
  var menu = new SlideMenu(win.document.getElementById('main-mobile-menu'), { 
    position: 'left',
    showBackLink: true,
    submenuLinkAfter: '<i class="menu-right-icon material-icons"> chevron_right </i>',
    backLinkBefore: '<i class="menu-right-icon material-icons"> chevron_left </i>'
  });


  menu.menu.addEventListener('sm.open-after', function () {
    win.document.getElementById('mobile-menu-overlay').classList.toggle('mobile-active');
    win.document.querySelector('body').classList.add('body-overflow');
  });
}
```
The error is on the word menu.menu `menu.menu.addEventListener` saying that menu.menu is null. This mean `new SlideMenu` is not initializing the menu.

in version 1.0.13 doing 
```
import SlideMenu from '@grubersjoe/slide-menu';
window.SlideMenu = SlideMenu;
new window.SlideMenu()
```
is not working and saying window.SlideMenu is not a constructor. Not sure about 1.1.3

Questions:
* Am I misusing this library or is it really breaking after the update?
* Just wondering If it is a breaking change, shouldn't the version be changed to 2.x.x as it is a major update? I am not a pro at versioning by the way :)))

PS. Thank you for this nice library. It really helped us on a project.

**Comment by grubersjoe** [comment]
Hey there,

thanks for the feedback and sorry that the upgrade broke this for you. Unfortunately this not, how an event handler for the menu should be added (or at least not, how I tought it should be). The `SlideMenu.menu` property has been renamed to `menuElem` in v1.1.3, so `SlideMenu.menu` is indeed null. I've never considered this property to be part of the public API to register an event handler. Therefore, I also havn't thought my refactoring would break the menu for anyone. But this issue and another clearly show, that it should really be better documented how to listen to events "correctly".

You should rather do it this way:

```js
var mainMenu = win.document.getElementById('main-mobile-menu');
var menu = new SlideMenu(mainMenu, { 
    position: 'left',
    showBackLink: true,
    submenuLinkAfter: '<i class="menu-right-icon material-icons"> chevron_right </i>',
    backLinkBefore: '<i class="menu-right-icon material-icons"> chevron_left </i>'
});

mainMenu.addEventListener('sm.open-after', function () {
    win.document.getElementById('mobile-menu-overlay').classList.toggle('mobile-active');
    win.document.querySelector('body').classList.add('body-overflow');
});
```
Does it work this way?

**Comment by peshrawahmed** [comment]
Silly me! :) you are obviously right. I could just bind the event to the DOM element instead of binding to menu.menu. 

Thank you. The issue can be closed.
