### ISSUE TITLE
Display: none when returning to parent

### ISSUE THREAD

**Issue by anaisabel19886** [grubersjoe/slide-menu#2]
Hi!

Sometimes, when going back from viewing the children menu, to the main menu; the parent of the children I just visited gets display:none inlined.. Any tips?

Thanks for the package!

**Comment by anaisabel19886** [comment]
I've solved this.
I was using the class active to highlight the current page; The package very likely checks for the active class to toggle the children/parent menus, and thus was hiding the current page from the menu, when the moved from the kids to the parent menu view.

Solution: use another class name to hightlight the current page.

**Comment by grubersjoe** [comment]
Hey,

thanks for pointing this out. You are absolutely right: The script looks for an `active` class, which really was not a very thoughtful choice for the name. I'm going to adapt the script in the next days 👍 .
