### ISSUE TITLE
Library not compatible in IE 11

### ISSUE THREAD

**Issue by prosperva** [grubersjoe/slide-menu#4]
This line `class SlideMenu {` throws a syntax error

**Comment by grubersjoe** [comment]
Are you using the files under `src`? These are written in ES6 and not meant for production. You should use the files under `dist`, which are transpiled by Babel to ES5 code (and therefore throw no syntax error).

If you want to modify the code and rebuild the library (to `dist`) run the following commands ([Gulp](https://gulpjs.com/) required):

```sh
npm install
gulp
```
