### ISSUE TITLE
HELP PLEASE!!! Integrate with wordpress and divi theme

### ISSUE THREAD

**Issue by nitofrerrer** [grubersjoe/slide-menu#40]
I need to integrate it with wordpress and divi theme please You're the only answer.

**Comment by grubersjoe** [comment]
GitHub issues are for problems in the project's code. I'm sorry if you can't get it to work inside your project, but this is not my responsibility and I'm not going to do your homework.

Also sending an email is not going to help either.

**Comment by nitofrerrer** [comment]
I didn't mean to offend i just wanted help as i'm completely new to code.
And my english is not the best either. But anyway could you please help me
out? I've tried everything.
BTW i just created a Github account so i don't know this platform either.
And this is not a homework

**Comment by nitofrerrer** [comment]
This is my profile https://github.com/nitofrerrer
