### ISSUE TITLE
Suggestion: Add rel attribute with nofollow value for the Back Link

### ISSUE THREAD

**Issue by rpb138** [grubersjoe/slide-menu#41]
This is just a suggestion because one of the scans/tests we run on our site reported an issue with the "Back" link. It gives us the following:

> Links are not crawlable
> 
> Search engines may use href attributes on links to crawl websites. Ensure that the href attribute of anchor elements links to an appropriate destination, so more pages of the site can be discovered. 

I think adding `rel="nofollow"` will help.

Thank you.

**Comment by grubersjoe** [comment]
Mmmh I don't think this will really fix the issue but will simply make search engines ignore the links in the menu which probably is not what you want. If not all pages are linked somehow else on the website the crawler will not be able to find all pages.

However, this project also is no longer maintained, I just keep it here if someone finds it still useful. So I think if you would like to have this functionality it would be best to fork it.
